/**
 * PolicyBind VS Code Extension
 *
 * Provides language support, validation, and IntelliSense for
 * PolicyBind AI governance policy files.
 */

import * as vscode from 'vscode';
import * as yaml from 'js-yaml';
import Ajv from 'ajv';
import * as path from 'path';
import * as fs from 'fs';

// Schema for validation
let policySchema: object | null = null;
let ajv: Ajv | null = null;

// Diagnostic collection for validation errors
let diagnosticCollection: vscode.DiagnosticCollection;

/**
 * Activate the extension
 */
export function activate(context: vscode.ExtensionContext) {
    console.log('PolicyBind extension is now active');

    // Initialize diagnostic collection
    diagnosticCollection = vscode.languages.createDiagnosticCollection('policybind');
    context.subscriptions.push(diagnosticCollection);

    // Load the JSON schema
    loadSchema(context);

    // Register commands
    registerCommands(context);

    // Register hover provider
    registerHoverProvider(context);

    // Register completion provider
    registerCompletionProvider(context);

    // Register document validation
    registerValidation(context);

    // Register code actions
    registerCodeActions(context);
}

/**
 * Load the policy JSON schema
 */
function loadSchema(context: vscode.ExtensionContext) {
    try {
        const schemaPath = path.join(
            context.extensionPath,
            'schemas',
            'policybind-policy.schema.json'
        );
        const schemaContent = fs.readFileSync(schemaPath, 'utf8');
        policySchema = JSON.parse(schemaContent);

        ajv = new Ajv({ allErrors: true, verbose: true });
        ajv.compile(policySchema);
    } catch (error) {
        console.error('Failed to load PolicyBind schema:', error);
    }
}

/**
 * Register extension commands
 */
function registerCommands(context: vscode.ExtensionContext) {
    // Validate current file
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.validateFile', () => {
            const editor = vscode.window.activeTextEditor;
            if (editor) {
                validateDocument(editor.document);
                vscode.window.showInformationMessage('PolicyBind: Validation complete');
            }
        })
    );

    // Validate all policies in workspace
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.validateWorkspace', async () => {
            const files = await vscode.workspace.findFiles(
                '**/*.policy.{yaml,yml}',
                '**/node_modules/**'
            );

            let errorCount = 0;
            for (const file of files) {
                const document = await vscode.workspace.openTextDocument(file);
                const errors = validateDocument(document);
                errorCount += errors;
            }

            vscode.window.showInformationMessage(
                `PolicyBind: Validated ${files.length} files, ${errorCount} errors found`
            );
        })
    );

    // Create new policy set
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.createPolicySet', async (uri: vscode.Uri) => {
            const name = await vscode.window.showInputBox({
                prompt: 'Enter policy set name',
                placeHolder: 'my-policy-set',
                validateInput: (value) => {
                    if (!/^[a-z0-9][a-z0-9-]*[a-z0-9]$/.test(value)) {
                        return 'Name must be lowercase alphanumeric with hyphens';
                    }
                    return null;
                }
            });

            if (!name) return;

            const template = `# PolicyBind Policy Set
# Generated by PolicyBind VS Code Extension

name: ${name}
version: 1.0.0
description: |
  Description of this policy set.
  Add details about its purpose and scope.

metadata:
  author: your-team
  environment: development
  # compliance:
  #   - SOC2
  #   - GDPR

rules:
  # Example: Allow all requests by default (low priority catch-all)
  - name: allow-all-default
    description: Default allow rule for all requests
    priority: 0
    enabled: true
    match_conditions: {}
    action: ALLOW

  # Example: Deny PII data to external providers
  # - name: deny-pii-external
  #   description: Block PII data from going to external AI providers
  #   priority: 100
  #   enabled: true
  #   match_conditions:
  #     data_classification:
  #       contains: pii
  #   action: DENY
  #   action_params:
  #     reason: PII data cannot be sent to external AI providers
`;

            const folderPath = uri?.fsPath || vscode.workspace.workspaceFolders?.[0]?.uri.fsPath;
            if (!folderPath) {
                vscode.window.showErrorMessage('No folder selected');
                return;
            }

            const filePath = path.join(folderPath, `${name}.policy.yaml`);
            fs.writeFileSync(filePath, template);

            const document = await vscode.workspace.openTextDocument(filePath);
            await vscode.window.showTextDocument(document);
        })
    );

    // Create new rule
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.createRule', async () => {
            const editor = vscode.window.activeTextEditor;
            if (!editor) {
                vscode.window.showErrorMessage('No active editor');
                return;
            }

            const name = await vscode.window.showInputBox({
                prompt: 'Enter rule name',
                placeHolder: 'my-rule-name'
            });

            if (!name) return;

            const action = await vscode.window.showQuickPick(
                ['ALLOW', 'DENY', 'MODIFY', 'REQUIRE_APPROVAL', 'RATE_LIMIT', 'AUDIT'],
                { placeHolder: 'Select action' }
            );

            if (!action) return;

            const ruleTemplate = `
  - name: ${name}
    description: Description of this rule
    priority: 100
    enabled: true
    match_conditions:
      # Add your conditions here
      provider: openai
    action: ${action}
    action_params:
      reason: Reason for this action
`;

            // Insert at cursor position
            editor.edit((editBuilder) => {
                editBuilder.insert(editor.selection.active, ruleTemplate);
            });
        })
    );

    // Format document
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.formatDocument', () => {
            const editor = vscode.window.activeTextEditor;
            if (editor) {
                vscode.commands.executeCommand('editor.action.formatDocument');
            }
        })
    );

    // Show documentation
    context.subscriptions.push(
        vscode.commands.registerCommand('policybind.showDocumentation', () => {
            vscode.env.openExternal(
                vscode.Uri.parse('https://policybind.io/docs')
            );
        })
    );
}

/**
 * Register hover provider for policy keywords
 */
function registerHoverProvider(context: vscode.ExtensionContext) {
    const hoverProvider = vscode.languages.registerHoverProvider(
        [{ scheme: 'file', pattern: '**/*.policy.{yaml,yml}' }, 'yaml'],
        {
            provideHover(document, position) {
                const wordRange = document.getWordRangeAtPosition(position, /[\w-]+/);
                if (!wordRange) return null;

                const word = document.getText(wordRange);
                const hoverContent = getHoverContent(word);

                if (hoverContent) {
                    return new vscode.Hover(hoverContent);
                }
                return null;
            }
        }
    );

    context.subscriptions.push(hoverProvider);
}

/**
 * Get hover content for a keyword
 */
function getHoverContent(word: string): vscode.MarkdownString | null {
    const docs: Record<string, string> = {
        // Top-level keys
        'name': '**Policy Set/Rule Name**\n\nUnique identifier. Use lowercase with hyphens.\n\nExample: `my-policy-set`',
        'version': '**Version**\n\nSemantic version of the policy set.\n\nExample: `1.0.0`',
        'description': '**Description**\n\nHuman-readable explanation of the policy or rule.',
        'metadata': '**Metadata**\n\nAdditional information about the policy set (author, environment, compliance).',
        'rules': '**Rules**\n\nList of policy rules in this set. Rules are evaluated in priority order.',
        'match_conditions': '**Match Conditions**\n\nConditions that determine when this rule applies.\n\nSupports: `provider`, `model`, `department`, `data_classification`, operators (`eq`, `contains`, `in`), and logical (`and`, `or`, `not`).',
        'action': '**Action**\n\nWhat to do when the rule matches.\n\n- `ALLOW` - Permit the request\n- `DENY` - Block the request\n- `MODIFY` - Allow but modify (e.g., redact PII)\n- `REQUIRE_APPROVAL` - Queue for approval\n- `RATE_LIMIT` - Apply rate limiting\n- `AUDIT` - Log without blocking',
        'action_params': '**Action Parameters**\n\nAdditional parameters for the action (reason, rate limits, modifications, etc.).',
        'priority': '**Priority**\n\nNumeric priority (higher = evaluated first).\n\nRange: -1000 to 1000\nDefault: 0',
        'enabled': '**Enabled**\n\nWhether the rule is active. Set to `false` to disable without removing.',
        'tags': '**Tags**\n\nList of tags for categorizing rules.\n\nExample: `[production, pii, compliance]`',

        // Match condition fields
        'provider': '**Provider Condition**\n\nMatch by AI provider.\n\nValues: `openai`, `anthropic`, `google`, `azure`, `aws`, `cohere`, `mistral`, `ollama`',
        'model': '**Model Condition**\n\nMatch by model name.\n\nExamples: `gpt-4`, `claude-3-opus`, `gemini-pro`',
        'department': '**Department Condition**\n\nMatch by user department.\n\nExamples: `engineering`, `marketing`, `legal`',
        'user_id': '**User ID Condition**\n\nMatch by specific user identifier.',
        'data_classification': '**Data Classification Condition**\n\nMatch by data sensitivity level.\n\nValues: `public`, `internal`, `confidential`, `restricted`, `pii`, `phi`, `financial`',
        'estimated_cost': '**Estimated Cost Condition**\n\nMatch by estimated request cost in USD.\n\nUse with operators: `gt`, `gte`, `lt`, `lte`',
        'estimated_tokens': '**Estimated Tokens Condition**\n\nMatch by estimated token count.\n\nUse with operators: `gt`, `gte`, `lt`, `lte`',

        // Operators
        'eq': '**Equals Operator**\n\nExact match.\n\n```yaml\nfield:\n  eq: value\n```',
        'ne': '**Not Equals Operator**\n\nDoes not match.\n\n```yaml\nfield:\n  ne: value\n```',
        'gt': '**Greater Than Operator**\n\nNumeric comparison.\n\n```yaml\nestimated_cost:\n  gt: 1.00\n```',
        'gte': '**Greater Than or Equal Operator**\n\n```yaml\nestimated_tokens:\n  gte: 1000\n```',
        'lt': '**Less Than Operator**\n\n```yaml\nestimated_cost:\n  lt: 10.00\n```',
        'lte': '**Less Than or Equal Operator**\n\n```yaml\nestimated_tokens:\n  lte: 5000\n```',
        'in': '**In List Operator**\n\nValue is in list.\n\n```yaml\nprovider:\n  in:\n    - openai\n    - anthropic\n```',
        'not_in': '**Not In List Operator**\n\nValue is not in list.\n\n```yaml\nmodel:\n  not_in:\n    - gpt-4\n    - claude-3-opus\n```',
        'contains': '**Contains Operator**\n\nString contains substring, or collection contains element.\n\n```yaml\ndata_classification:\n  contains: pii\n```',
        'matches': '**Regex Match Operator**\n\nMatches regular expression pattern.\n\n```yaml\nmodel:\n  matches: "^gpt-4.*"\n```',

        // Logical operators
        'and': '**AND Logic**\n\nAll conditions must match.\n\n```yaml\nand:\n  - provider: openai\n  - department: engineering\n```',
        'or': '**OR Logic**\n\nAt least one condition must match.\n\n```yaml\nor:\n  - provider: openai\n  - provider: anthropic\n```',
        'not': '**NOT Logic**\n\nNegate a condition.\n\n```yaml\nnot:\n  department: engineering\n```',

        // Actions
        'ALLOW': '**ALLOW Action**\n\nPermit the request to proceed unchanged.',
        'DENY': '**DENY Action**\n\nBlock the request. Include a `reason` in action_params.',
        'MODIFY': '**MODIFY Action**\n\nAllow but modify the request.\n\nConfigure `modifications` in action_params (e.g., `redact_pii`).',
        'REQUIRE_APPROVAL': '**REQUIRE_APPROVAL Action**\n\nQueue for human approval before proceeding.\n\nConfigure `approval` in action_params.',
        'RATE_LIMIT': '**RATE_LIMIT Action**\n\nApply rate limiting.\n\nConfigure `rate_limit` in action_params.',
        'AUDIT': '**AUDIT Action**\n\nLog the request without blocking.\n\nConfigure `audit` in action_params.',
    };

    const content = docs[word];
    if (content) {
        const md = new vscode.MarkdownString(content);
        md.isTrusted = true;
        return md;
    }
    return null;
}

/**
 * Register completion provider
 */
function registerCompletionProvider(context: vscode.ExtensionContext) {
    const completionProvider = vscode.languages.registerCompletionItemProvider(
        [{ scheme: 'file', pattern: '**/*.policy.{yaml,yml}' }, 'yaml'],
        {
            provideCompletionItems(document, position) {
                const lineText = document.lineAt(position).text;
                const linePrefix = lineText.substring(0, position.character);

                const completions: vscode.CompletionItem[] = [];

                // Action values
                if (linePrefix.match(/action:\s*$/)) {
                    const actions = ['ALLOW', 'DENY', 'MODIFY', 'REQUIRE_APPROVAL', 'RATE_LIMIT', 'AUDIT', 'REDIRECT'];
                    actions.forEach(action => {
                        const item = new vscode.CompletionItem(action, vscode.CompletionItemKind.EnumMember);
                        item.detail = `PolicyBind action: ${action}`;
                        completions.push(item);
                    });
                }

                // Provider values
                if (linePrefix.match(/provider:\s*$/)) {
                    const providers = ['openai', 'anthropic', 'google', 'azure', 'aws', 'cohere', 'mistral', 'ollama', 'huggingface'];
                    providers.forEach(provider => {
                        const item = new vscode.CompletionItem(provider, vscode.CompletionItemKind.Value);
                        item.detail = `AI Provider: ${provider}`;
                        completions.push(item);
                    });
                }

                // Data classification values
                if (linePrefix.match(/data_classification:\s*$/)) {
                    const classifications = ['public', 'internal', 'confidential', 'restricted', 'pii', 'phi', 'financial'];
                    classifications.forEach(cls => {
                        const item = new vscode.CompletionItem(cls, vscode.CompletionItemKind.Value);
                        item.detail = `Data classification: ${cls}`;
                        completions.push(item);
                    });
                }

                // Match condition keys
                if (linePrefix.match(/match_conditions:\s*$/) || linePrefix.match(/^\s+-?\s*$/)) {
                    const conditions = [
                        { name: 'provider', desc: 'Match by AI provider' },
                        { name: 'model', desc: 'Match by model name' },
                        { name: 'department', desc: 'Match by user department' },
                        { name: 'user_id', desc: 'Match by user identifier' },
                        { name: 'data_classification', desc: 'Match by data classification' },
                        { name: 'source_application', desc: 'Match by application' },
                        { name: 'estimated_cost', desc: 'Match by estimated cost' },
                        { name: 'estimated_tokens', desc: 'Match by token count' },
                        { name: 'and', desc: 'All conditions must match' },
                        { name: 'or', desc: 'Any condition must match' },
                        { name: 'not', desc: 'Negate a condition' },
                    ];
                    conditions.forEach(cond => {
                        const item = new vscode.CompletionItem(cond.name, vscode.CompletionItemKind.Field);
                        item.detail = cond.desc;
                        item.insertText = new vscode.SnippetString(`${cond.name}: `);
                        completions.push(item);
                    });
                }

                // Operators
                if (linePrefix.match(/^\s+\w+:\s*$/)) {
                    const operators = [
                        { name: 'eq', desc: 'Equals' },
                        { name: 'ne', desc: 'Not equals' },
                        { name: 'gt', desc: 'Greater than' },
                        { name: 'gte', desc: 'Greater than or equal' },
                        { name: 'lt', desc: 'Less than' },
                        { name: 'lte', desc: 'Less than or equal' },
                        { name: 'in', desc: 'Value in list' },
                        { name: 'not_in', desc: 'Value not in list' },
                        { name: 'contains', desc: 'Contains substring/element' },
                        { name: 'not_contains', desc: 'Does not contain' },
                        { name: 'matches', desc: 'Regex match' },
                    ];
                    operators.forEach(op => {
                        const item = new vscode.CompletionItem(op.name, vscode.CompletionItemKind.Operator);
                        item.detail = op.desc;
                        item.insertText = new vscode.SnippetString(`\n    ${op.name}: `);
                        completions.push(item);
                    });
                }

                return completions;
            }
        },
        ':', ' '
    );

    context.subscriptions.push(completionProvider);
}

/**
 * Register document validation
 */
function registerValidation(context: vscode.ExtensionContext) {
    // Validate on open
    vscode.workspace.onDidOpenTextDocument((document) => {
        if (isPolicyFile(document)) {
            validateDocument(document);
        }
    }, null, context.subscriptions);

    // Validate on save
    vscode.workspace.onDidSaveTextDocument((document) => {
        const config = vscode.workspace.getConfiguration('policybind');
        if (config.get('validation.onSave') && isPolicyFile(document)) {
            validateDocument(document);
        }
    }, null, context.subscriptions);

    // Validate on change (debounced)
    let validationTimeout: NodeJS.Timeout | undefined;
    vscode.workspace.onDidChangeTextDocument((event) => {
        const config = vscode.workspace.getConfiguration('policybind');
        if (config.get('validation.onType') && isPolicyFile(event.document)) {
            if (validationTimeout) {
                clearTimeout(validationTimeout);
            }
            validationTimeout = setTimeout(() => {
                validateDocument(event.document);
            }, 500);
        }
    }, null, context.subscriptions);

    // Clear diagnostics when document closes
    vscode.workspace.onDidCloseTextDocument((document) => {
        diagnosticCollection.delete(document.uri);
    }, null, context.subscriptions);
}

/**
 * Check if document is a policy file
 */
function isPolicyFile(document: vscode.TextDocument): boolean {
    const config = vscode.workspace.getConfiguration('policybind');
    const patterns = config.get<string[]>('filePatterns') || [];

    const relativePath = vscode.workspace.asRelativePath(document.uri);

    for (const pattern of patterns) {
        const regex = new RegExp(
            pattern
                .replace(/\*\*/g, '.*')
                .replace(/\*/g, '[^/]*')
                .replace(/\./g, '\\.')
        );
        if (regex.test(relativePath)) {
            return true;
        }
    }

    return false;
}

/**
 * Validate a policy document
 */
function validateDocument(document: vscode.TextDocument): number {
    const config = vscode.workspace.getConfiguration('policybind');
    if (!config.get('validation.enabled')) {
        return 0;
    }

    const diagnostics: vscode.Diagnostic[] = [];
    const text = document.getText();

    try {
        // Parse YAML
        const policy = yaml.load(text) as Record<string, unknown>;

        if (!policy) {
            diagnostics.push(
                new vscode.Diagnostic(
                    new vscode.Range(0, 0, 0, 0),
                    'Empty policy file',
                    vscode.DiagnosticSeverity.Warning
                )
            );
        } else {
            // Validate structure
            validatePolicyStructure(policy, document, diagnostics);
        }
    } catch (error) {
        if (error instanceof yaml.YAMLException) {
            const line = error.mark?.line || 0;
            const col = error.mark?.column || 0;
            diagnostics.push(
                new vscode.Diagnostic(
                    new vscode.Range(line, col, line, col + 10),
                    `YAML syntax error: ${error.message}`,
                    vscode.DiagnosticSeverity.Error
                )
            );
        }
    }

    diagnosticCollection.set(document.uri, diagnostics);
    return diagnostics.filter(d => d.severity === vscode.DiagnosticSeverity.Error).length;
}

/**
 * Validate policy structure
 */
function validatePolicyStructure(
    policy: Record<string, unknown>,
    document: vscode.TextDocument,
    diagnostics: vscode.Diagnostic[]
) {
    // Check required fields
    if (!policy.name) {
        addDiagnostic(document, diagnostics, 'name', 'Missing required field: name', vscode.DiagnosticSeverity.Error);
    }

    if (!policy.version) {
        addDiagnostic(document, diagnostics, 'version', 'Missing required field: version', vscode.DiagnosticSeverity.Error);
    }

    if (!policy.rules) {
        addDiagnostic(document, diagnostics, 'rules', 'Missing required field: rules', vscode.DiagnosticSeverity.Error);
    } else if (!Array.isArray(policy.rules)) {
        addDiagnostic(document, diagnostics, 'rules', 'rules must be an array', vscode.DiagnosticSeverity.Error);
    } else {
        // Validate each rule
        const ruleNames = new Set<string>();
        (policy.rules as Record<string, unknown>[]).forEach((rule, index) => {
            validateRule(rule, index, document, diagnostics, ruleNames);
        });
    }

    // Validate version format
    if (policy.version && typeof policy.version === 'string') {
        if (!/^\d+\.\d+\.\d+(-[a-zA-Z0-9.-]+)?$/.test(policy.version)) {
            addDiagnostic(
                document,
                diagnostics,
                'version',
                'version should follow semantic versioning (e.g., 1.0.0)',
                vscode.DiagnosticSeverity.Warning
            );
        }
    }
}

/**
 * Validate a single rule
 */
function validateRule(
    rule: Record<string, unknown>,
    index: number,
    document: vscode.TextDocument,
    diagnostics: vscode.Diagnostic[],
    ruleNames: Set<string>
) {
    const rulePrefix = `rules[${index}]`;

    // Check required fields
    if (!rule.name) {
        addDiagnostic(document, diagnostics, rulePrefix, 'Rule missing required field: name', vscode.DiagnosticSeverity.Error);
    } else {
        // Check for duplicate names
        if (ruleNames.has(rule.name as string)) {
            addDiagnostic(document, diagnostics, rule.name as string, `Duplicate rule name: ${rule.name}`, vscode.DiagnosticSeverity.Error);
        }
        ruleNames.add(rule.name as string);
    }

    if (!rule.action) {
        addDiagnostic(document, diagnostics, rulePrefix, 'Rule missing required field: action', vscode.DiagnosticSeverity.Error);
    } else {
        // Validate action value
        const validActions = ['ALLOW', 'DENY', 'MODIFY', 'REQUIRE_APPROVAL', 'RATE_LIMIT', 'AUDIT', 'REDIRECT'];
        if (!validActions.includes(rule.action as string)) {
            addDiagnostic(
                document,
                diagnostics,
                rule.action as string,
                `Invalid action: ${rule.action}. Must be one of: ${validActions.join(', ')}`,
                vscode.DiagnosticSeverity.Error
            );
        }
    }

    // Validate priority range
    if (rule.priority !== undefined) {
        const priority = rule.priority as number;
        if (priority < -1000 || priority > 1000) {
            addDiagnostic(
                document,
                diagnostics,
                'priority',
                'priority should be between -1000 and 1000',
                vscode.DiagnosticSeverity.Warning
            );
        }
    }

    // Warn if action is DENY but no reason provided
    if (rule.action === 'DENY') {
        const params = rule.action_params as Record<string, unknown> | undefined;
        if (!params?.reason) {
            addDiagnostic(
                document,
                diagnostics,
                rule.name as string || rulePrefix,
                'DENY action should include a reason in action_params',
                vscode.DiagnosticSeverity.Warning
            );
        }
    }
}

/**
 * Add a diagnostic at the location of a keyword
 */
function addDiagnostic(
    document: vscode.TextDocument,
    diagnostics: vscode.Diagnostic[],
    searchText: string,
    message: string,
    severity: vscode.DiagnosticSeverity
) {
    const text = document.getText();
    const index = text.indexOf(searchText);

    let range: vscode.Range;
    if (index >= 0) {
        const position = document.positionAt(index);
        range = new vscode.Range(position, position.translate(0, searchText.length));
    } else {
        range = new vscode.Range(0, 0, 0, 0);
    }

    const diagnostic = new vscode.Diagnostic(range, message, severity);
    diagnostic.source = 'PolicyBind';
    diagnostics.push(diagnostic);
}

/**
 * Register code actions
 */
function registerCodeActions(context: vscode.ExtensionContext) {
    const codeActionProvider = vscode.languages.registerCodeActionsProvider(
        [{ scheme: 'file', pattern: '**/*.policy.{yaml,yml}' }],
        {
            provideCodeActions(document, range, context) {
                const actions: vscode.CodeAction[] = [];

                // Provide quick fixes for diagnostics
                for (const diagnostic of context.diagnostics) {
                    if (diagnostic.message.includes('DENY action should include a reason')) {
                        const fix = new vscode.CodeAction(
                            'Add reason to action_params',
                            vscode.CodeActionKind.QuickFix
                        );
                        fix.diagnostics = [diagnostic];
                        fix.edit = new vscode.WorkspaceEdit();
                        // This is a simplified fix - a real implementation would be more sophisticated
                        actions.push(fix);
                    }
                }

                return actions;
            }
        }
    );

    context.subscriptions.push(codeActionProvider);
}

/**
 * Deactivate the extension
 */
export function deactivate() {
    if (diagnosticCollection) {
        diagnosticCollection.dispose();
    }
}
